# this is an example config that works for Arctis Nova 7
# optional fields can be commented out with the '#' character

name = "Arctis Nova 7"
product_id = 0x2202
# optional, HID interface number
interface_num = 3                 
# what bytes should be written to device to get battery status
# only the first 2 bytes are read
write_bytes = [0x00, 0xb0]
# some devices require a very specific read buf size
# commonly 6, 8 or any power of 2
read_buf_size = 8
battery_percent_idx = 2
battery_range = [0x00, 0x04]      # min=0, max=4
charging_status_idx = 3           # optional

# optional, used for connecting to the correct device.
# Every headset has multiple HID devices.
# Windows has a way to connect to the correct device using a vendor-specific usage page and id
usage_page_and_id = [0xffc0, 0x1] 

# optional, used when connected and charging idx are separate (Arctis 9)
# connected_status_idx = 1