name: Release
on:
  push:
    tags: "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: |
            **/target
          key: Cargo.lock

      - run: cargo build --release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss

      - run: Compress-Archive Output\mysetup.exe arctis-battery-indicator.zip
        shell: powershell

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            arctis-battery-indicator.zip

          generate_release_notes: true
          name: Release ${{github.ref_name}}
