name: Release
on:
  push:
    tags: "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - run: mv target/release/*.exe .

      - run: Compress-Archive -Path *.exe,Install.ps1 -DestinationPath arctis-battery-indicator-${{github.ref_name}}.zip
        shell: powershell

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            arctis-battery-indicator-${{github.ref_name}}.zip

          generate_release_notes: true
          draft: true
          name: Release ${{github.ref_name}}
