name: Release
on:
  push:
    tags: "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: |
            **/target
          key: Cargo.lock

      - run: cargo build --release

      - run: mv target/release/*.exe .

      - run: Compress-Archive *.exe Install.ps1 arctis-battery-indicator-${{github.ref_name}}.zip
        shell: powershell

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            arctis-battery-indicator-${{github.ref_name}}.zip

          generate_release_notes: true
          name: Release ${{github.ref_name}}
